# Generated by Django 5.0.1 on 2024-01-16 18:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_dp_image')),
                ('cover_picture', models.ImageField(blank=True, upload_to='profile_cover_image')),
                ('bio', models.TextField(blank=True)),
                ('joined', models.DateTimeField(default=datetime.datetime.now)),
                ('interests', models.CharField(blank=True, max_length=1000)),
                ('followers', models.ManyToManyField(blank=True, related_name='profile_followers', to='dathway_app.profile')),
                ('following', models.ManyToManyField(blank=True, related_name='profile_following', to='dathway_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
