# Generated by Django 5.0.1 on 2024-02-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dathway_app', '0002_messages_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
