# Generated by Django 5.0.1 on 2024-02-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathway_app', '0003_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to='dathway_app.profile'),
        ),
    ]
